sonar.projectKey=2mino
sonar.projectName=2mino

sonar.sources=src,api-integracion/src,ms-usuarios/src,ms-frontend-landing/src,ms-salas/src
sonar.tests=ms-salas/src
sonar.test.inclusions=**/*.test.ts

sonar.exclusions=**/dist/**,**/node_modules/**,**/*.test.ts
sonar.sourceEncoding=UTF-8

# Cobertura (si se agrega vitest --coverage a futuro):
# sonar.javascript.lcov.reportPaths=ms-salas/coverage/lcov.info
